import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-7xl mx-auto">
        <h1 className="text-center p-4 text-3xl font-bold underline">
          SimpleSystems.pl
        </h1>
      </div>
    </div>
  );
}
